site_name: Siddhi IO S3
site_description: Siddhi IO S3 Extension
repo_name: Siddhi IO S3
repo_url: https://github.com/siddhi-io/siddhi-io-s3/
edit_uri: https://github.com/siddhi-io/siddhi-io-s3/blob/master/
copyright: Siddhi - Documentation
theme:
  name: material
  logo: images/siddhi-logo.svg
  favicon: images/favicon.ico
  palette:
    primary: teal
    accent: teal
extra_css:
- assets/stylesheets/extra.css
extra_javascript:
- assets/javascripts/extra.js
extra:
  social:
  - type: github
    link: https://github.com/siddhi-io/siddhi
  - type: medium
    link: https://medium.com/siddhi-io
  - type: twitter
    link: https://twitter.com/siddhi_io
  - type: linkedin
    link: https://www.linkedin.com/groups/13553064
google_analytics:
- UA-103065-28
- auto
markdown_extensions:
- markdown.extensions.admonition
pages:
- Welcome: index.md
- API Docs:
  - latest: api/latest.md
  - 1.0.0: api/1.0.0.md
  - ? ''
    : api/.md
- License: license.md
